name: macOS TkinterDnD2 Test

on:
  push:
  pull_request:

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python 3.13 using pyenv
        run: |
          brew update
          brew install pyenv
          pyenv install 3.13.0
          pyenv global 3.13.0
          echo "PYENV_ROOT=$HOME/.pyenv" >> $GITHUB_ENV
          echo "$HOME/.pyenv/bin" >> $GITHUB_PATH
          echo "$HOME/.pyenv/shims" >> $GITHUB_PATH
          python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run TkinterDnD2 test script
        run: |
          python -c "from tkinterdnd2 import TkinterDnD; root = TkinterDnD.Tk(); root.mainloop()"
